### ISSUE TITLE
Heterogeneous effects between studies

### ISSUE THREAD

**Issue by wavefancy** [yaowuliu/ACAT#1]
Hi yaowu,

Is this possible to deal with heterogeneous effects between studies? As the weights and p values are non-negative, have no idea how to deal with this. Specifically, can I have negative weight,  as for some studies, they may have opposite effects? 

Thanks much!
Wallace

**Comment by yaowuliu** [comment]
Hi Wallace,

Sorry for the delayed response. I did not check this page for a while. As p-value loses the information about effect direction, I would suggest to combine test statistics instead of p-values, e.g., using the Burden test. In this p-value combination method, you cannot have negative weights. Thanks.

Yaowu
